// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library MiscMagma {
  // http://www.magmascan.org/address/0xF90255EE9DD2A0fA7E0a9ffd44Ef44D4282C6eF5
  address internal constant PROXY_ADMIN = 0xF90255EE9DD2A0fA7E0a9ffd44Ef44D4282C6eF5;

  // http://www.magmascan.org/address/0x28b09ea80D94f835B2d1A1AB1810a790EAB40190
  address internal constant PROTOCOL_GUARDIAN = 0x28b09ea80D94f835B2d1A1AB1810a790EAB40190;
}
